name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - name: Display Dependencies
        run: ./gradlew dependencies --info

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --info --refresh-dependencies

      - name: Publish JAR
        uses: actions/upload-artifact@v4
        with:
          name: SimpleClaimSystem
          path: build/libs/*.jar
